dependencies:
  - ipykernel
  - sphinx >= 1.4
  - scikit-learn
  - numpy
  - scipy
  - holidays
  - lxml <= 3.6.1
  - pandas >= 0.18,<0.19
  - patsy
  - pytz
  - requests
  - pip:
    - nbsphinx
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
